"""Classify commit authors as human, bot, or AI agent.

This enables per-commit analysis within hybrid repos, turning each repo
into a natural experiment comparing human vs. agent coding patterns.

Classification hierarchy:
1. Known AI coding agents (Claude, Copilot agent, Devin, Jules)
2. Known automation bots (dependabot, renovate, github-actions, pre-commit-ci)
3. Project-specific bots (clawdinator, openclaw-bot, latitude-bot)
4. Everything else → human
"""

from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

from code_ontology.config import PROCESSED_DIR


# ── Pattern definitions ──────────────────────────────────────────────

# AI coding agents — these write substantive code
AI_AGENT_PATTERNS: list[re.Pattern] = [
    re.compile(r"copilot@users\.noreply\.github\.com", re.I),
    re.compile(r"anthropic-code-agent\[bot\]", re.I),
    re.compile(r"claude@users\.noreply\.github\.com", re.I),
    re.compile(r"google-labs-jules\[bot\]", re.I),
    re.compile(r"devin-ai", re.I),
    re.compile(r"openclaw-bot", re.I),
    re.compile(r"clawdinator\[bot\]", re.I),
    re.compile(r"clawdbot", re.I),
    re.compile(r"bot@clawd", re.I),
    re.compile(r"bot@latitude\.io", re.I),
    re.compile(r"obitabot", re.I),
    re.compile(r"harrington-bot", re.I),
    re.compile(r"dobbylorenzbot", re.I),
    re.compile(r"bartokmoltbot", re.I),
]

# Automation bots — CI, dependency updates, formatting
AUTOMATION_BOT_PATTERNS: list[re.Pattern] = [
    re.compile(r"dependabot", re.I),
    re.compile(r"renovate", re.I),
    re.compile(r"github-actions\[bot\]", re.I),
    re.compile(r"pre-commit-ci\[bot\]", re.I),
    re.compile(r"blacksmith-sh\[bot\]", re.I),
    re.compile(r"greenkeeper", re.I),
    re.compile(r"snyk", re.I),
    re.compile(r"codecov", re.I),
    re.compile(r"imgbot", re.I),
    re.compile(r"allcontributors", re.I),
    re.compile(r"release-please", re.I),
    re.compile(r"semantic-release", re.I),
    re.compile(r"mergify", re.I),
    re.compile(r"stalebot", re.I),
    re.compile(r"depfu", re.I),
    re.compile(r"pyup-bot", re.I),
]


@dataclass
class AuthorLabel:
    category: str  # "human", "ai_agent", "automation_bot"
    confidence: str  # "pattern_match", "heuristic"
    matched_pattern: str | None = None


def classify_author(name: str, email: str) -> AuthorLabel:
    """Classify an author as human, ai_agent, or automation_bot."""
    combined = f"{name} {email}"

    # Check AI agent patterns first
    for pattern in AI_AGENT_PATTERNS:
        if pattern.search(combined):
            return AuthorLabel("ai_agent", "pattern_match", pattern.pattern)

    # Check automation bot patterns
    for pattern in AUTOMATION_BOT_PATTERNS:
        if pattern.search(combined):
            return AuthorLabel("automation_bot", "pattern_match", pattern.pattern)

    # Heuristic: [bot] suffix in name or email
    if "[bot]" in name.lower() or "[bot]" in email.lower():
        return AuthorLabel("automation_bot", "heuristic", "[bot] in name/email")

    # Heuristic: "bot" as a standalone word in the author name — default to automation
    # (AI agents are only identified by specific known patterns above)
    if re.search(r"\bbot\b", name, re.I) and "robot" not in name.lower():
        return AuthorLabel("automation_bot", "heuristic", "bot in name")

    return AuthorLabel("human", "default")


# ── Commit message patterns for AI agent detection ──────────────────
# These catch agents using human developer emails (developer prompted the agent)

COMMIT_MSG_AI_PATTERNS: list[tuple[re.Pattern, str]] = [
    # Claude Code footers / co-author
    (re.compile(r"\[Claude Code\]\(https://claude\.com", re.I), "claude_code_footer"),
    (re.compile(r"Co-Authored-By:\s*Claude", re.I), "claude_coauthor"),
    (re.compile(r"Agent-Logs-Url:", re.I), "agent_logs_url"),
    # Copilot agent
    (re.compile(r"Co-authored-by:.*copilot", re.I), "copilot_coauthor"),
    (re.compile(r"Co-authored-by:.*github-copilot", re.I), "copilot_coauthor"),
    # Devin
    (re.compile(r"Generated by Devin", re.I), "devin_footer"),
    (re.compile(r"Co-authored-by:.*devin-ai", re.I), "devin_coauthor"),
    # Cursor
    (re.compile(r"<!-- Cursor -->", re.I), "cursor_marker"),
    (re.compile(r"cursor\.com", re.I), "cursor_footer"),
    # Aider
    (re.compile(r"aider:.*", re.I), "aider_prefix"),
    (re.compile(r"Co-authored-by:.*aider", re.I), "aider_coauthor"),
    # Generic AI markers
    (re.compile(r"Co-authored-by:.*\[bot\]", re.I), "bot_coauthor"),
]


def classify_commit_message(message: str) -> AuthorLabel | None:
    """Check commit message for AI agent footers/markers. Returns None if no match."""
    for pattern, label in COMMIT_MSG_AI_PATTERNS:
        if pattern.search(message):
            return AuthorLabel("ai_agent", "commit_message", label)
    return None


def classify_commits(commits: list[dict]) -> list[dict]:
    """Add author_category field to each commit dict."""
    for c in commits:
        # First check author name/email
        label = classify_author(c.get("author_name", ""), c.get("author_email", ""))
        # If classified as human by default, check commit message for AI markers
        if label.confidence == "default":
            msg_label = classify_commit_message(c.get("message", ""))
            if msg_label:
                label = msg_label
        c["author_category"] = label.category
        c["author_confidence"] = label.confidence
        c["author_matched"] = label.matched_pattern
    return commits


def compute_author_classification_stats(commits: list[dict]) -> dict:
    """Compute summary statistics of author classification for a specimen."""
    classified = classify_commits(commits)

    # Overall counts
    category_counts = Counter(c["author_category"] for c in classified)
    total = len(classified)

    # Per-category metrics
    categories = {}
    for cat in ["human", "ai_agent", "automation_bot"]:
        cat_commits = [c for c in classified if c["author_category"] == cat]
        if not cat_commits:
            categories[cat] = {
                "num_commits": 0,
                "pct_commits": 0,
                "num_authors": 0,
                "total_churn": 0,
                "avg_files_per_commit": 0,
                "avg_churn_per_commit": 0,
                "unique_files": 0,
            }
            continue

        authors = set()
        total_files_per_commit = []
        total_churn = 0
        all_files: set[str] = set()

        for c in cat_commits:
            authors.add(c.get("author_email", ""))
            files = [f["path"] for f in c["files"]]
            total_files_per_commit.append(len(files))
            churn = c.get("total_insertions", 0) + c.get("total_deletions", 0)
            total_churn += churn
            all_files.update(files)

        n = len(cat_commits)
        categories[cat] = {
            "num_commits": n,
            "pct_commits": round(n / total * 100, 2) if total else 0,
            "num_authors": len(authors),
            "total_churn": total_churn,
            "avg_files_per_commit": round(sum(total_files_per_commit) / n, 2) if n else 0,
            "avg_churn_per_commit": round(total_churn / n, 2) if n else 0,
            "unique_files": len(all_files),
        }

    # Top bot/agent authors
    agent_authors: dict[str, int] = defaultdict(int)
    bot_authors: dict[str, int] = defaultdict(int)
    for c in classified:
        if c["author_category"] == "ai_agent":
            agent_authors[f"{c.get('author_name', '')} <{c.get('author_email', '')}>"] += 1
        elif c["author_category"] == "automation_bot":
            bot_authors[f"{c.get('author_name', '')} <{c.get('author_email', '')}>"] += 1

    # Detection method breakdown
    confidence_counts = Counter(c.get("author_confidence", "unknown") for c in classified)
    matched_patterns = Counter(
        c.get("author_matched", "none") for c in classified
        if c.get("author_matched")
    )

    return {
        "total_commits": total,
        "categories": categories,
        "top_agent_authors": [
            {"author": a, "commits": n}
            for a, n in sorted(agent_authors.items(), key=lambda x: -x[1])[:10]
        ],
        "top_bot_authors": [
            {"author": a, "commits": n}
            for a, n in sorted(bot_authors.items(), key=lambda x: -x[1])[:10]
        ],
        "detection_methods": {
            "by_confidence": dict(confidence_counts),
            "by_pattern": dict(matched_patterns.most_common(20)),
        },
    }


def save_author_classification(data: dict, specimen_name: str) -> Path:
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    out_path = PROCESSED_DIR / f"{specimen_name}_authors.json"
    out_path.write_text(json.dumps(data, indent=2))
    print(f"  saved author classification → {out_path}")
    return out_path
